const data=	[
   {
      "id":28,
      "Title":"Sweden",
      "image":"./images/Red.jpeg",
      "details":{
         "price":5000,
         "size":"s",
         "color":"red",
      }
   },
   {
      "id":56,
      "Title":"USA",
      "image":"./images/White.jpeg",
"details":{
         "price":5000,
         "size":"s",
         "color":"white",
      }
   },
   ]